### ISSUE TITLE
issue 1 is looking ~beautiful~

### ISSUE THREAD

**Issue by jumblesale** [tildetown/zine#18]
so honoured

**Comment by maxhebditch** [comment]
I'll try and fix this issue.

**Comment by jumblesale** [comment]
please no

**Comment by Sanqui** [comment]
I'm pretty sure this is a feature

**Comment by maxhebditch** [comment]
ill contribute more FAM imagery to bring down the beauty.

**Comment by MineRobber9000** [comment]
not so sure I want the beauty to end.
