### ISSUE TITLE
Issue 2 seems empty

### ISSUE THREAD

**Issue by MineRobber9000** [tildetown/zine#23]
There isn't much in Issue 2. We need more stuff or a print run won't be worth it. What we do have looks good, it's just that there isn't much to print.

**Comment by Sanqui** [comment]
Aaaaa, I'm definitely gonna do something soon!

**Comment by MineRobber9000** [comment]
As an aside, it took almost 2 months for issue 1, and we're going on 4 months for issue 2. Hope this exponential growth of time taken doesn't continue.

(seriously though, tommorrow will be exactly 4 months since I added the issue 2 folder to the repo)

**Comment by MineRobber9000** [comment]
Alright, I'm thinking we should have @jumblesale get to work on the issue, seeing as how the last addition was about a month ago. Any thoughts?

**Comment by jumblesale** [comment]
I agree, I will work on getting this out to everyone in the new year x

**Comment by MineRobber9000** [comment]
As @jumblesale is working on the issue, I'm closing this. (forgot to do it back then)
