### ISSUE TITLE
Could we please have some clarification for those not used to using Github?

### ISSUE THREAD

**Issue by mejoemejoe** [tildetown/zine#27]
## I'm a newbie at Github, and I'd like to contribute but I don't know how.

**Comment by RussellChamp** [comment]
https://help.github.com/articles/creating-a-pull-request/ is one way but i think @jumblesale also had added people as direct contributors which allow for pushes right to main

**Comment by jumblesale** [comment]
hey mejoemejoe, you're absolutely right, the documentation does not help someone who is not used to github. I will try to add instructions this weekend. if they are not clear please let me know, we want the zine to be as inclusive as possible!

**Comment by phtan** [comment]
Hey mejoemejoe, do you find the following guide helpful?

'how the heck do I use github'. http://lifehacker.com/5983680/how-the-heck-do-i-use-github

**Comment by jumblesale** [comment]
hey @mejoemejoe sorry I didn't get chance to write this up but in the meantime you can do this to quickly add something to the zine:
- navigate to the current issue (https://github.com/tildetown/zine/tree/master/issue_2)
- at the top of the screen is a white button which says "upload files"
- upload the file you wanted to contribute
- optionally give it a commit message
- hit commit changes

this should work ok! let us know in here if it does not.

**Comment by MineRobber9000** [comment]
seeing as how the discussion is over, and it's now 2017, I'm closing this, if that's okay?
