### ISSUE TITLE
Where did everything go?

### ISSUE THREAD

**Issue by MineRobber9000** [tildetown/zine#28]
jumblesale's latest commit seems to have deleted everything except "contributing.md" and "readme.md". Where is everything? Do we need to reset to a previous commit? (was this a mistake?)

There were no additions in that commit,btw - just deletions. Proof:

![image](https://cloud.githubusercontent.com/assets/12676241/20119420/782a57f6-a5d6-11e6-8df9-af06bb228216.png)

**Comment by MineRobber9000** [comment]
I've restored everything, just in case this was a mistake.

**Comment by jumblesale** [comment]
whoops sorry! I was trying to move it because you can't use github's `upload file` stuff if the directory has a space in the name (it ends up creating a new directory with `%20`s in it). all fixed now!
