### ISSUE TITLE
When should we stop accepting entries for an issue?

### ISSUE THREAD

**Issue by MineRobber9000** [tildetown/zine#33]
I'm curious. Obviously, the latest limit is the print run, but should we stop accepting entries for an issue before the print run?

**Comment by l0010o0001l** [comment]
How often are issues distributed?

**Comment by MineRobber9000** [comment]
currently, whenever we decide we have enough. my idea is a release schedule of about 3 months (4 a year)
between issues. if an issue is deemed to be uncomplete, it becomes stalled until the next release. I think I'll implement the 3 month release schedule if there aren't any objections from our designer @jumblesale. (issue 3, for example, should be released in december of 2017 (no way it'll be ready in September) unless we don't have enough stuff)

Also, as an aside, what happens if contributions run out? I would think we release what had at that point and close submissions. Any suggestions?

**Comment by MineRobber9000** [comment]
this issue is stale. closing.
